num_dog = 3
version = '1.1.2'

[[Zhou]]
name = 'BuDing'
adopted = true
age = 4
weight = 15.6
height = 30.0

    [Zhou.options]
    pose = [0.1,0.2,0.3]


[[Zhou]]
name = 'DuoDuo'
adopted = true
age = 3.5
weight = 15.6
height = 29.8

    [Zhou.options]
    pose = [1.1,1.2,1.3]

[[Zhou]]
name = 'PaoPao'
adopted = false
age = 6
weight = 28.2
height = 50.1

    [Zhou.options]
    pose = [0.01,0.02,0.03]
